packages:
  - packages/config/eslint
  - packages/config/tsconfig
  - packages/config/prettier
  - packages/config/jest
  - packages/common
  - algorithms/*/
  - data-structures/*/
  - containers/*/
  - LC/*/
