packages:
  - packages/config/eslint
  - packages/config/tsconfig
  - packages/config/prettier
  - packages/config/jest
  - packages/common
  - algorithms/*/
  - algorithms/*/__bench__/
  - data-structures/*/
  - data-structures/*/__bench__/
  - containers/*/
  - containers/*/__bench__/
  - LC/*/
